package ui.login;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import dto.AdminDTO;
import enumeration.ResponseCode;
import enumeration.Role;
import service.general.LoginService;
import service.general.SessionControlService;
import ui.dashboard.AdminDashboard;

/**
 *
 * @author Alex Tho
 */
public class LoginInterface extends JFrame {

	private Role role = Role.ADMIN;

	/** Creates new form LoginInterface */
	public LoginInterface() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoleGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdminRoleRadioButton = new javax.swing.JRadioButton();
        ManagerRoleRadioButton = new javax.swing.JRadioButton();
        CustomerRoleRadioButton = new javax.swing.JRadioButton();
        VendorRoleRadioButton = new javax.swing.JRadioButton();
        RunnerRoleRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome to FoodHero!");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        RoleGroup.add(AdminRoleRadioButton);
        AdminRoleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AdminRoleRadioButton.setSelected(true);
        AdminRoleRadioButton.setText("Admin");
        AdminRoleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminRoleRadioButtonActionPerformed(evt);
            }
        });

        RoleGroup.add(ManagerRoleRadioButton);
        ManagerRoleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ManagerRoleRadioButton.setText("Manager");
        ManagerRoleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerRoleRadioButtonActionPerformed(evt);
            }
        });

        RoleGroup.add(CustomerRoleRadioButton);
        CustomerRoleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CustomerRoleRadioButton.setText("Customer");
        CustomerRoleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerRoleRadioButtonActionPerformed(evt);
            }
        });

        RoleGroup.add(VendorRoleRadioButton);
        VendorRoleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VendorRoleRadioButton.setText("Vendor");
        VendorRoleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendorRoleRadioButtonActionPerformed(evt);
            }
        });

        RoleGroup.add(RunnerRoleRadioButton);
        RunnerRoleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RunnerRoleRadioButton.setText("Runner");
        RunnerRoleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunnerRoleRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Email Address  : ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Password         : ");

        EmailField.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        EmailField.setForeground(new java.awt.Color(204, 204, 204));
        EmailField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EmailField.setToolTipText("Enter your email here ...");
        EmailField.setMaximumSize(new java.awt.Dimension(64, 31));

        PasswordField.setToolTipText("Enter your password here ...");
        PasswordField.setMaximumSize(new java.awt.Dimension(64, 31));
        PasswordField.setMinimumSize(new java.awt.Dimension(64, 31));
        PasswordField.setPreferredSize(new java.awt.Dimension(64, 31));

        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManagerRoleRadioButton)
                            .addComponent(CustomerRoleRadioButton)
                            .addComponent(VendorRoleRadioButton)
                            .addComponent(RunnerRoleRadioButton))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(LoginButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(AdminRoleRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(129, 129, 129)
                .addComponent(AdminRoleRadioButton)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ManagerRoleRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerRoleRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(VendorRoleRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(RunnerRoleRadioButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(LoginButton)
                        .addGap(179, 179, 179))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void AdminRoleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
		role = Role.ADMIN;
	}                                                 

	private void VendorRoleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
		role = Role.VENDOR;
	}                                                  

	private void RunnerRoleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
		role = Role.RUNNER;
	}                                                  

	private void CustomerRoleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
		role = Role.CUSTOMER;
	} 

	private void ManagerRoleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
		role = Role.MANAGER;
	}

	private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
		String email = EmailField.getText();
		String password = new String(PasswordField.getPassword());

		if (role == null) {
			JOptionPane.showMessageDialog(null, "Please select a role. ");
		} else if (email.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Please enter your email. ");
		} else if (password.isEmpty()) {
			JOptionPane.showMessageDialog(null, "Please enter your password. ");
		} else if (!LoginService.validateEmail(email)) {
			JOptionPane.showMessageDialog(null, "Please enter a valid email address. ");
		} else {
			System.out.println("Role: " + role + ", Email: " + email);

			// authentication logic here
			ResponseCode code = LoginService.login(role, email, password);
			
			if (code == ResponseCode.RECORD_NOT_FOUND) {
				JOptionPane.showMessageDialog(null, "Login failed. Please try again. ");
			}
			
			if (code == ResponseCode.IO_EXCEPTION) {
				JOptionPane.showMessageDialog(null, "Error reading from file. Please try again. ");
			}
			
			if (code == ResponseCode.SUCCESS) {
				JOptionPane.showMessageDialog(null, "Login successful! ");
				
				// Open respective dashboard based on the role
				switch (role) {
			    case ADMIN -> new AdminDashboard((AdminDTO) SessionControlService.getUser()).setVisible(true);
//			    case MANAGER -> new ManagerDashboard(user).setVisible(true);
//			    case CUSTOMER -> new CustomerDashboard(user).setVisible(true);
//			    case VENDOR -> new VendorDashboard(user).setVisible(true);
//			    case RUNNER -> new RunnerDashboard(user).setVisible(true);
			    default -> JOptionPane.showMessageDialog(null, "Unknown error occured. Please try again. ");
				}

			    // Close or hide the login window
			    this.dispose();
			}
		}
	}//GEN-LAST:event_LoginButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginInterface().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AdminRoleRadioButton;
    private javax.swing.JRadioButton CustomerRoleRadioButton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton LoginButton;
    private javax.swing.JRadioButton ManagerRoleRadioButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.ButtonGroup RoleGroup;
    private javax.swing.JRadioButton RunnerRoleRadioButton;
    private javax.swing.JRadioButton VendorRoleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
